/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_cognito_identity_pool_id": "us-east-2:7a9b90d9-24b0-40a4-b81d-1a44ade21d57",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_Hu65oi5Xu",
    "aws_user_pools_web_client_id": "4afa4f3q5e2ud1vnq6d6d3dscd",
    "oauth": {},
    "aws_user_files_s3_bucket": "gvod-dev-input-ihv97pr4",
    "aws_user_files_s3_bucket_region": "us-east-2"
};


export default awsmobile;
